config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  devise_for :users
  resources :users, only: [:show], controllers: {registrations: 'registrations'}

  resources :bookings
  resources :animals do
    resources :reviews, only: :create
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :bookings, only: [] do
    member do
      patch '/accept', to: 'bookings#accept'
      patch '/decline', to: 'bookings#decline'
    end
  end
end

app/models/animal.rb
class Animal < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many :reviews, dependent: :destroy

  SPECIES = ["Dog", "Cat", "Bird", "Hamster"]
  validates :species, inclusion: { in: SPECIES }
  validates :species, :name, :location, :availability_start, :availability_end, :photo, presence: true

  geocoded_by :location
  mount_uploader :photo, PhotoUploader

  after_validation :geocode, if: :will_save_change_to_location?
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  validates :start_date, :end_date, presence: true
  belongs_to :user
  belongs_to :animal
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :animal

  RATING = [1, 2, 3, 4, 5]
  validates :rating, inclusion: { in: RATING }
  validates :description, length: { minimum: 5 }
  validates :description, :rating, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # DO NOT REMOVE THIS COMMENT UNLESS YOU ARE READY TO FIX THE DB!!!
  # validates :first_name, presence: true
  mount_uploader :avatar, AvatarUploader
  
  has_many :animals, dependent: :destroy
  has_many :bookings, dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  before_action :animal_find, only: %i[edit update show destroy]
  skip_before_action :authenticate_user!, only: %i[index show]

  def index
    # @animals = Animal.all

    if params[:query].present?
      sql_query = "animals.species @@ :query OR animals.location @@ :query OR animals.name @@ :query"
      @animals = Animal.where(sql_query, query: "%#{params[:query]}%")
    else
      @animals = Animal.geocoded # Animal.wherenot(lat:nil, lng: nil)
    end

    # if params[:location].present?
    #   sql_query = "animals.location @@ :location"
    #   @animals = Animal.where(sql_query, location: "%#{params[:location]}%")
    # else
    #   @animals = Animal.geocoded
    # end

    @markers = @animals.map do |animal|
      {
        lat: animal.latitude,
        lng: animal.longitude,
        potato: animal.id,
        infoWindow: render_to_string(partial: "info_window", locals: { animal: animal })
      }
    end
  end

  def new
    @animal = Animal.new
  end

  def show
    @user = current_user
    @booking = Booking.new
    @reviews = Review.all
  end

  def create
    @animal = Animal.new(animal_params)
    @animal.user = current_user
    if @animal.save
      redirect_to user_path(current_user)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @animal.update(animal_params)
  end

  def destroy
    @animal.destroy
    respond_to do |format|
      format.html { user_path(current_user) } #if js not working respond with html
      format.js # <-- will render `app/views/reviews/create.js.erb`
    end
  end

  private

  def animal_find
    @animal = Animal.find(params[:id])
  end

  def animal_params
    params.require(:animal).permit(:species, :name, :characteristics, :availability_start, :availability_end, :location, :photo, :price)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?


  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :remember_me, :avatar, :avatar_cache, :remove_avatar])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :avatar, :avatar_cache, :remove_avatar])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :booking_find, only: [:edit, :update, :show, :destroy, :accept, :decline]

  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.animal = Animal.find(animal_id)
    if @booking.save
      redirect_to user_path(current_user)
    else
      render "animal/show"
    end
  end

  def edit
  end

  def update
  end

  def destroy
    @booking.destroy
    redirect_to user_path(current_user)
  end

  def accept
    @booking.update(status: "accepted")
    respond_to do |format|
      format.html { user_path(current_user) } #if js not working respond with html
      format.js # <-- will render `app/views/bookings/create.js.erb`
    end
  end

  def decline
    @booking.update(status: "declined")
    respond_to do |format|
      format.html { user_path(current_user) } #if js not working respond with html
      format.js # <-- will render `app/views/bookings/create.js.erb`
    end
  end

  private

  def booking_find
    @booking = Booking.find(params[:id])
  end

  def animal_params
    params.require(:booking).permit(:animal, :user, :start_date, :end_date)
  end

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end

  def animal_id
    params.require(:booking).permit(:animal)[:animal]
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @booking = Booking.new
    @review = Review.new(review_params)
    @animal = Animal.find(params[:animal_id])
    @review.animal = @animal

    if @review.save
      respond_to do |format|
        format.html { redirect_to animal_path(@animal) }
        format.js  # render `app/views/reviews/create.js.erb`
      end
    else
      respond_to do |format|
        format.html { render 'animals/show' }
        format.js  # render `app/views/reviews/create.js.erb`
      end
    end
  end

  private

  def review_params
    params.require(:review).permit(:description, :rating)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @bookings = current_user.bookings
    allbookings = Booking.all
    @requests = []
    @animals = []
    current_user.animals.each do |animal|
      @animals << animal.id
    end
    allbookings.each do |booking|
      @requests << booking if @animals.include?(booking.animal_id)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/animals/_form.html.erb
<div class="animal-new-background">
  <div class='container'>
    <div class="create-animal">
      <h1>Let's get started listing your pet</h1>
      <div class="create-form">
        <div class="input-form">
<!--           <h3>Step 1</h3> -->
          <%= simple_form_for(@animal) do |f| %>
          <%= f.input :name %>
          <%= f.input :species, collection: Animal::SPECIES %>
          <%= f.input :characteristics, as: :text, input_html: {rows: 4} %>
          <%= f.input :price%>
          <%= f.input :location%>
          <%= f.input :availability_start%>
          <%= f.input :availability_end%>
          <%= f.input :photo %>
          <%= f.input :photo_cache, as: :hidden, class:"button-primary" %>
          <%= f.submit 'Create', class:"button-primary"%>
          <% end %>
        </div>
        <div>
        </div>

      </div>
    </div>
  </div>
</div>

app/views/animals/_info_window.html.erb
<div class="cards-popup">
  <%= link_to animal_path(animal) do %>
  <div class="card-trip">
    <%= cl_image_tag animal.photo %>
    <div class="card-trip-infos">
       <div>
         <h2><%= animal.name %></h2>
         <p><%= animal.species %></p>
       </div>
        <p class="card-trip-pricing">
        <%= animal.location %>
        </p>
    </div>
  </div>
  <% end %>
</div>

app/views/animals/_review.html.erb
<div class="d-flex justify-content-between">
  <div><i><p>"<%=review.description%>"</p></i></div>
  <div>
    <%review.rating.times do%>
      <i class="fas fa-star"></i>
    <%end%>
    <%(5 - review.rating).times do%>
      <i class="far fa-star"></i>
    <%end%>
  </div>
</div>

app/views/animals/destroy.js.erb
myAnimalToDelete = document.querySelector("[data-animal-id='<%= @animal.id %>']")
// 2. I delete the restaurant by calling the js function remove.
myAnimalToDelete.remove()

app/views/animals/edit.html.erb
<%= render 'form', animal: @animal %>

app/views/animals/index.html.erb
<div class="container-index">
  <div class="all-wrapper">
    <div class="animal-wrapper container">
      <p><%= @animals.count %> pets to foster</p>
      <div class='cards-animal-index'>
        <% @animals.each do |animal| %>
        <%= link_to animal_path(animal) do %>
          <div class="card-animal-trip">
            <%= cl_image_tag animal.photo %>
             <div class="card-animal-trip-infos">
               <div>
                 <h2><%= animal.name %></h2>
                 <p><%= animal.species %></p>
               </div>
               <h2 class="card-trip-pricing"><%= animal.price %>€ / day</h2>
             </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
    <div
      id="map";
      class="map-wrapper";
      data-markers="<%= @markers.to_json %>"
      data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
    ></div>
  </div>
</div>

app/views/animals/new.html.erb
<div class="animal-new-background">
  <div class='container'>
    <div class="create-animal">
      <h1>Hi<%#= current_user.name.capitalize %>! Let's get started listing your pet</h1>
      <div class="create-form">
        <div class="input-form">
          <h3>Step 1</h3>
          <%= simple_form_for(@animal) do |f| %>
          <%= f.input :name %>
          <%= f.input :species, collection: Animal::SPECIES %>
          <%= f.input :characteristics, as: :text, input_html: {rows: 4} %>
          <%= f.input :price%>
          <%= f.input :location%>
          <%= f.input :availability_start%>
          <%= f.input :availability_end%>
          <%= f.input :photo %>
          <%= f.input :photo_cache, as: :hidden, class:"button-primary" %>
          <%= f.submit 'Create', class:"button-primary"%>
          <% end %>
        </div>
        <div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/animals/show.html.erb
<div class="container">
  <div class="row"> <!--Dividing the screen in 2-->
    <div class="col-8"> <!--First half of the screen-->

      <%= cl_image_tag(@animal.photo, class: "w-100 mb-3") %>

      <div class="card">
        <h1><%=@animal.name%></h1>
        <p class="mb-0">Species: <%=@animal.species%></p>
        <div class="d-flex justify-content-between">
          <p>Located in <%=@animal.location%></p>
          <p><%=@animal.user.avatar%></p>
        </div>
      </div>


      <div class="card">
        <h4>Description </h4>
        <i><p>"<%=@animal.characteristics%>"</p></i>
      </div>

      <div class="card">
        <div>
          <h4>Reviews</h4>
          <p class="text-secondary"><%=pluralize @animal.reviews.size, "review"%> about <%=@animal.name%></p>
        </div>

        <div class="border-bottom mb-4">
          <div id="reviews">
            <%if @animal.reviews.blank?%>
              <p>Be the first to leave a review for <%=@animal.name%></p>
            <%else%>
              <%@animal.reviews.each do |review|%>
                <%= render "animals/review", review: review %>
              <%end%>
          <%end%>
          </div>
        </div>

        <div>
          <p>How did you like <%=@animal.name%>?</p>
          <%=render "reviews/form", animal: @animal, review: Review.new %>
        </div>
        <%= link_to "<i class='fas fa-arrow-left'></i>".html_safe, animals_path, class: "mt-5 mb-2 text-secondary" %>
      </div>
    </div>

    <div class="col-4"> <!--Second half of the screen-->
      <div class="sticky-top card justify-content-center">
        <div class="border-bottom mb-4">
          <h2>Booking</h2>
          <p>Enter the dates on which you would want to book the <%=@animal.species%> <%=@animal.name%></p>
        </div>

        <div>
          <%=render "bookings/form"%>
        </div>

      </div>
    </div>
  </div>
</div>

app/views/bookings/_form.html.erb
<%=simple_form_for (@booking) do |f|%>
  <%=f.input :start_date %>
  <%=f.input :end_date %>
  <%=f.hidden_field :animal, value: @animal.id%>
  <%=f.submit "Book", class: "button-calltoaction" %>
<%end%>

app/views/bookings/accept.js.erb
document.querySelector("[data-request-id='<%= @booking.id %>'] .booking-status").innerHTML = "accepted"

app/views/bookings/decline.js.erb
document.querySelector("[data-request-id='<%= @booking.id %>'] .booking-status").innerHTML = "declined"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>🐱 AirPet 🐶</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <link href="https://fonts.googleapis.com/css?family=Montserrat&display=swap" rel="stylesheet">
    <%= stylesheet_pack_tag 'application', media: 'all' %>
    <script src="https://api.tiles.mapbox.com/mapbox-gl-js/v1.6.0/mapbox-gl.js"></script>
    <link href="https://api.tiles.mapbox.com/mapbox-gl-js/v1.6.0/mapbox-gl.css" rel=‘stylesheet’ />
  </head>
  <body>
    <%= render 'components/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<html class="home-page">
  <div class="container mt-5 col-3 selector-options-background">
    <h1 class="text-black">Find a pet</h1>
    <p class="text-black">Where you can share your pet with other people that aren't lucky enough to have their own</p>
    <div class="row px-3">
      <%= form_tag animals_path, method: :get, class:"flex-grow-1" do %>
        <label class="text-black">Location</label>
        <%= text_field_tag :location,
        params[:location], id:'animal_address',
        class: "form-control mb-1", placeholder: "City" %>
        <label class="text-black">Pet</label>
        <%= select_tag :species, options_for_select(Animal::SPECIES), class: "form-control mb-1" %>
        <label class="text-black">Pickup date</label>
        <%= date_field_tag :start_date,
        params[:start_date], class: "form-control mb-1",
        placeholder: Date.current, value: Date.current%>
        <label class="text-black">Return date</label>
        <%= date_field_tag :end_date,
        params[:end_date], class: "form-control",
        placeholder: Date.current, value: Date.tomorrow %>
        <%= submit_tag "Find your Pet", class: "button-home mt-3 mb-2" %>
      <% end %>
    </div>
  </div>
</div>

app/views/reviews/_form.html.erb
<%=simple_form_for([animal, review], remote: true) do |f|%>
  <%=f.input :rating, collection: Review::RATING %>
  <%=f.input :description %>
  <%=f.submit "Post review", class: "button-primary mx-0"%>
<%end%>

app/views/reviews/create.js.erb
function refreshForm(innerHTML) {
  const newReviewForm = document.getElementById('new_review');
  newReviewForm.innerHTML = innerHTML;
}

function addReview(reviewHTML) {
  const reviews = document.getElementById('reviews');
  reviews.insertAdjacentHTML('beforeend', reviewHTML);
}


<% if @review.errors.any? %>
  refreshForm('<%=j render "reviews/form", animal: @animal, review: @review%>');
<% else %>
  addReview('<%=j render "animals/review", review: @review%>');
  refreshForm('<%= j render "reviews/form", animal: @animal, review: Review.new%>');
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_shared.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/users/_animals.html.erb
<% if current_user.animals.present? %>
  <div class="pet-header">
    <h3 class="my-pets-cards">My pets
    <%= link_to new_animal_path do  %>
      <i class="fas fa-plus"></i>
    <% end %>
    </h3>
    <div class='cards'>
      <%  current_user.animals.each do |animal|%>
      <div class="card-trip" data-animal-id="<%=animal.id%>">
        <%= link_to animal_path(animal) do  %>
          <%= cl_image_tag animal.photo %>
        <% end %>
        <div class="card-trip-infos align-items-start">
          <div>
            <h2><%= animal.name %></h2>
            <p><%= animal.species %></p>
          </div>
          <div class="card-trip-pricing text-right animal-price-font d-flex flex-column" >
            <%= animal.price %>€/day
            <div>
              <%= link_to edit_animal_path(animal) do%>
                <i class="far fa-edit"></i>
              <% end %>
              <%= link_to animal_path(animal), method: :delete, remote: true, data: { confirm: "Are you sure?" } do %>
                <i class="far fa-trash-alt"></i>
            </div>
            <% end %>
          </div>
         </div>
      </div>
      <% end %>
    </div>
  </div>
<% else %>
<%= %>
<% end %>

app/views/users/_bookings.html.erb
<div class="pet-header">
  <h3 class="my-pets-cards">My Bookings
    <%= link_to root_path do  %>
    <i class="fas fa-plus"></i>
  <% end %></h3>
  <div class='cards'>
    <%current_user.bookings.each do |booking|%>
      <div class="card-trip">
        <%= link_to animal_path(booking.animal) do  %>
        <%= cl_image_tag booking.animal.photo %>
        <% end %>
        <div class="card-trip-infos">
          <div>
          <h2><%= booking.animal.name %></h2>
          <p><%= booking.animal.species %></p>
          </div>
          <p class="card-trip-pricing text-right  d-flex align-self-start"> Status: <%= booking.status %></p>
        </div>
          <p class="pl-2 pb-1"><%= booking.start_date %>~<%= booking.end_date %></p>
      </div>
    <% end %>
</div>

app/views/users/_requests.html.erb
<% if @requests.present? %>
  <div class="pet-header">
    <h3 class="my-pets-cards">My Requests
      <%= link_to root_path do  %>
      <i class="fas fa-plus"></i>
    <% end %></h3>
    <div class='cards'>
      <%@requests.each do |request|%>
        <div class="card-trip">
          <%= link_to user_path(request.user_id) do  %>
          <%= cl_image_tag request.animal.photo %>
          <% end %>
          <div class="card-trip-infos d-flex">
            <div class= "small-bottom-padding">
              <h2><%= request.animal.name %></h2>
              <p><%= request.animal.species %></p>
            </div>
            <div class="card-trip-pricing text-right d-flex flex-column" data-request-id='<%= request.id %>'>
              <p> Status: <span class="booking-status"><%= request.status %></span></p>
              <div class="text-right d-flex flex-row-reverse ">
                <div class="pl-2">
                  <%= link_to accept_booking_path(request),method: :patch, remote: true do  %>
                    <i class="fas fa-check"></i>
                  <% end %>
                </div>
                <%= link_to decline_booking_path(request), method: :patch, remote: true do  %>
                  <i class="far fa-times-circle"></i>
                <% end %>
              </div>
             </div>
            </div>
          <p class="pl-2 pb-1"><%= request.start_date %>~<%= request.end_date %></p>
        </div>
      <% end %>
    </div>
  </div>
<% else %>
  <%=  %>
<% end %>

app/views/users/show.html.erb
<div class="container">
  <div class="row user-info">
    <div class="col-12 col-md-6 d-flex justify-content-center">
      <% if current_user.avatar.present? %>
          <%= cl_image_tag current_user.avatar,class: "avatar-profile"%>
        <% else %>
          <%= cl_image_tag "https://i2.wp.com/smk.org.uk/wp-content/uploads/avatar.jpg?fit=300%2C300&ssl=1", class: "avatar-profile" %>
        <% end %>
    </div>
    <div class="description col-12 col-md-6 ">
      <h1>Hello <%= current_user.first_name %>,</h1>
      <br>
      <p>I am the owner of the Barcelona Animal Rescue shelter. The pets that come into my shelter deserve attention and love. When you choose to foster a pet from our shelter, you will be changing the quality of life for a little animal. Most of our animals come from the streets of Barcelona. They often come to us malnourished and lack of affection for an extended amount of time.</p>
      <%#= current_user.description %>
    </div>
  </div>
  <%= render "animals" %>
  <%= render "bookings" %>
  <%= render "requests" %>
</div>